version: '3'
services:
  pbapp:
    build:
      context: ./pbapp
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./pbapp:/app
    ports:
      - '4173:4173'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - HOSTNAME=localhost
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '4321:4321'
    command: npm run serve
  